name: SharpProj

on:
  push:
    branches: [ main, stable/* ]
  pull_request:
    branches: [ main, stable/* ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: SharpProj/src/SharpProj.sln

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        path: SharpProj

    - name: Build proj via VCPKG
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 030cfaa24de9ea1bbf0a4d9c615ce7312ba77af1
        vcpkgArguments: --overlay-ports=${{ github.workspace }}\SharpProj\vcpkg_ports proj4:x64-windows-static-md proj4:x86-windows-static-md

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1
      
    - name: Restore NuGet package (legacy style, vcxproj only)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore SharpProj\src\SharpProj\SharpProj.vcxproj -SolutionDirectory SharpProj\src

    - name: Build-x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /restore /p:Platform=x86 /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - name: Build-x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /restore /p:Platform=x64 /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - name: VSTest-x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vstest.console.exe /InIsolation /Platform:x86 SharpProj/src/SharpProj.Tests/bin/x86/Release/SharpProj.Tests.dll "--testcasefilter:TestCategory!=NeedsNetwork"

    - name: VSTest-x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: vstest.console.exe /InIsolation /Platform:x64 SharpProj/src/SharpProj.Tests/bin/x64/Release/SharpProj.Tests.dll "--testcasefilter:TestCategory!=NeedsNetwork"
